introspection:
  url: http://localhost:8000/graphql/  # یا آدرس endpoint گراف‌کیوال تو

info:
  title: simpledjango GraphQL API
  description: مستندات API پروژه جنگوی شما با GraphQL
  version: 1.0.0



theme:
  primaryColor: "#0d9488"


#outputDir: ./graphql-docs  # پوشه‌ای که مستندات HTML داخلش تولید میشه
##output:
##  path: templates/docs/